apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: elasticsearch
spec:
  podSelector:
    matchLabels:
      io.kompose.network/elasticsearch: "true"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: {{ .Values.ELASTICSEARCH_ENDPOINT_IP }}/32
      ports:
        - port: 9200
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.ELASTICSEARCH_ENDPOINT_IP }}/32
      ports:
        - port: 9200
