version: '3'

services:

  backend:
    build:
      context: backend
      dockerfile: ../out-of-tree/backend/docker/Dockerfile
    image: catalog_backend_api:latest
    ports:
      - "3031:3031"
    volumes:
      - ./conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro
      - webroot:/var/www/html
    links:
      - mariadb
      - rabbit
    external_links:
      - confd:yangcatalog.org

  yang-search:
    build:
      context: search
      dockerfile: ../out-of-tree/search/docker/Dockerfile
    ports:
      - "8005:8005"
    links:
      - mariadb
    volumes:
      - ./conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro

  yangre:
    build:
      context: yangre
      dockerfile: ../out-of-tree/yangre/docker/Dockerfile
    ports:
      - "5000:5000"

  api-receiver:
    image: catalog_backend_api:latest
    command: ["python", "api/receiver.py"]
    volumes:
      - ./conf/yangcatalog.conf:/etc/yangcatalog/yangcatalog.conf:ro
    links:
      - rabbit

  frontend:
    build:
      context: .
      dockerfile: out-of-tree/web_root/docker/Dockerfile
    volumes:
      - webroot:/usr/share/nginx/html
      - ./search/static/:/usr/share/nginx/html/yang-search/static/
      - ./yangre/app/static/:/usr/share/nginx/html/yangre/static/
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - backend
      - yang-search
      - yangre
      - elasticsearch
      - php
    ports:
      - "8080:8080"

  php:
    build:
      context: web_root
      dockerfile: ../out-of-tree/web_root/docker/PHP-Dockerfile
    volumes:
      - ./web_root:/scripts:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #volumes:
    #  - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
    volumes: []
      #- "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"

  mariadb:
    image: mariadb:10-bionic
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql:rw
      - ./conf/mariadb:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: yang_catalog
      MYSQL_USER: yang
      MYSQL_PASSWORD: fubar

volumes:
  dbdata:
  webroot:
