apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: confd
spec:
  podSelector:
    matchLabels:
      io.kompose.network/confd: "true"
  policyTypes:
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/confd: "true"
  egress:
    - to:
        - podSelector:
            matchLabels:
              io.kompose.network/confd: "true"
