apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: downloadables-pvc
  name: downloadables-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
