apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: webroot-pvc
  name: webroot-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
