apiVersion: v1
kind: Secret
metadata:
  name: yangcatalog-secret
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.MYSQL_ROOT_PASSWORD | b64enc }}
  MYSQL_USER: {{ .Values.MYSQL_USER | b64enc }}
  MYSQL_PASSWORD: {{ .Values.MYSQL_PASSWORD | b64enc }}
  RABBITMQ_USER: {{ .Values.RABBITMQ_USER | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.RABBITMQ_PASSWORD | b64enc }}
