apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: yang-search
  name: yang-search
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: yang-search
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/frontend: "true"
        io.kompose.network/mysql: "true"
        io.kompose.network/elasticsearch: "true"
        io.kompose.service: yang-search
    spec:
      securityContext:
        fsGroup: {{ .Values.YANG_GID }}
      containers:
      - image: 378723218809.dkr.ecr.eu-central-1.amazonaws.com/yc_yang-search:latest
        name: yang-search
        volumeMounts:
        - mountPath: /etc/yangcatalog/yangcatalog.conf
          name: yangcatalog-conf-pv
          readOnly: true
        - mountPath: /var/yang
          name: yang-resources-pv
        - mountPath: /var/run/yang
          name: run-pv
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
      - name: yangcatalog-conf-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}/conf/yangcatalog.conf
      - name: yang-resources-pv
        hostPath:
          path: {{ .Values.YANG_RESOURCES }}
      - name: run-pv
        persistentVolumeClaim:
          claimName: run-pvc
