apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend
spec:
  podSelector:
    matchLabels:
      io.kompose.network/backend: "true"
  policyTypes:
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/backend: "true"
  egress: []
